### ISSUE TITLE
Authenticate user only with username ?

### ISSUE THREAD

**Issue by barbuslex** [wells/l4-ldap-ntlm#4]
Hi,

Is it possible to authenticate user only with username ?

If the user exists in active directory (ldap) he got access to the website...

Is it possible to filter access on ldap group ?

Thanks

**Comment by wells** [comment]
It is possible, but this plugin is setup for NTLM Windows authentication to do so. The computer visiting would need to be on the domain for this to work with a properly configured browser. `auto()` found in `Wells\L4LdapNtlm\L4LdapNtlmGuard` handles this using the server var REMOTE_USER to auto negotiate. I had a tutorial on my blog, and I'll have to get that back up there again.

In addition, `validateCredentials()` under `Wells\L4LdapNtlm\L4LdapNtlmUserProvider` will require a password at all times. You could modify this function to merely `retrieveByCredentials()` instead of `ldap_bind` I leave that up to you because this is an auth package.

**Comment by barbuslex** [comment]
Ok thanks

I use this apache mod for get the `$_SERVER['REMOTE_USER']` variable : 
http://sourceforge.net/projects/mod-auth-sspi/

It's work with l4-ldap-ntlm ?

**Comment by wells** [comment]
Probably. I would assume that it would work, if the mod does set the same `$SERVER['REMOTEUSER']` var.

**Comment by barbuslex** [comment]
Ok thanks i will try it
